Check for one-elt array holding list, convert list to value
TopoFlow uses Numpy arrays for all internal variables, including
scalars. At some point (my hunch is in the Babelized `set_value`
method), a one-element list, instead of a single value, was set as
data for a variable, and caused type mismatches; e.g.:

```
File "/.../topoflow/components/snow_base.py", line 467, in update_swe
    self.h_swe -= dh2_swe
ValueError: non-broadcastable output operand with shape () doesn't match the broadcast shape (1,)
```

I added a check for this in TopoFlow's `set_value`, and converted the
one-element list into a scalar value.